<?php

/**
 * Include db operation functions.
 */
module_load_include('inc', 'unilogin', 'unilogin.db');

/**
 * Implements hook_init.
 */
function unilogin_init(){
  // Make this configurable instead:
  module_load_include('inc', 'unilogin', 'unilogin.vars');
  if(!_unilogin_is_in_unilogin_callback_state()) return;
  _unilogin_authenticate($_GET['user']);
}

function _unilogin_authenticate($user_id){
  
  $varnames = array(
    'unilogin_active',
    'unilogin_path_ws_infotjeneste',
    'unilogin_wsbrugerid',
    'unilogin_wspassword',
  );
  // All the needed drupal variables has to be present before we continue.
  if(!_unilogin_check_vars($varnames)) return;
  // Set the soap client.
  // Throws error in drupal_set_message if anything goes wrong.
  try {
    $Client = new SoapClient(variable_get('unilogin_path_ws_infotjeneste', ''));
  } catch (SoapFault $ex) {
    drupal_set_message($ex->faultstring, 'error');
    return;
  }
  // Web service access credentials.
  $ws_credentials = array(
    'brugerid' => $user_id,
    'wsPassword' => variable_get('unilogin_wspassword', ''),
    "wsBrugerid"=> variable_get('unilogin_wsbrugerid', '')
  );
  
  $person = $Client->hentPerson($ws_credentials);
  $unilogin_id = $person->return->Brugerid;
  // Check if the unilogin exists in our system.
  $uid = _unilogin_db_load_uid_by_unilogin_id($unilogin_id);
  // If unilogin id is not registered do nothing.
  if(!$uid) return;
  // Load user.
  $account = user_load($uid);
  // If the user load fails do nothing.
  if(empty($account)) return;
  // Login user.
  user_external_login($account);
  // Redirect user to get rid of unwanted $_GET params.
  drupal_goto($_GET['q'] != 'node' ? $_GET['q'] : '');
}

/**
 * Implements hook_block.
 */
function unilogin_block ($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks[0]['info'] = t('Unilogin');
      $blocks[0]['cache'] = BLOCK_NO_CACHE;
      return $blocks;
      break;
  case 'view':
    $block = array('title' => '', 'content' => '');
    $varnames = array(
      'unilogin_active',
      'unilogin_id',
      'unilogin_path_login',
      'unilogin_path_return',
      'unilogin_token_auth'
    );
    // If user is logged in
    // or if one ore more variables needed are empty/undefined return empty block;
    if (user_is_logged_in() || !_unilogin_check_vars($varnames)) return $block;
    // Otherwise show a link to Unilogin.
    $block['content'] = _unilogin_link();
    
    return $block;
    break;
  }
}

/**
 * A variable testing function.
 * 
 * @param array $varnames
 *  The names of the variables to test.
 * @param string $mode
 *  Which testing mode are we using?
 * @return boolean
 *   The test either passes or fails.
 */
function _unilogin_check_vars($varnames, $mode='all_set'){
  switch ($varnames){
    case 'all_set':
      foreach($varnames as $varname){
        if(!variable_get($varname, FALSE)) return FALSE;
      }
      break;
  }
  return TRUE;
    
}

/**
 * Renders a link to the verification site.
 * 
 * @return string
 *  HTML.
 */
function _unilogin_link(){
  $query_params = array(
    'id' => variable_get('unilogin_id', ''),
    'path' => variable_get('unilogin_path_return', ''),
    'auth' => variable_get('unilogin_token_auth', ''),
  );
  $query = '';
  array_walk(
    $query_params,
    function($value, $key) use (&$query){
      $query .= "$key=$value&";
    }
  );
  return '<h3>' . t('Login via') . ':</h3>' . l(
    theme(
      'image',
      drupal_get_path('module', 'unilogin') . '/images/uni-login-16pt.png'
    ),
    variable_get('unilogin_path_login', ''),
    array('query' => $query, 'html' => TRUE)
  );
}

/**
 * User edit form alter function.
 * 
 * @param array $form
 *   Drupal form array.
 * @param array $form_state
 *   Drupal form state array.
 */
function unilogin_form_user_profile_form_alter(&$form, &$form_state){
  $user = $form['_account']['#value'];
  $unilogin_id_db = _unilogin_db_load_unilogin_id_by_uid($user->uid);
  $unilogin_id = !empty($unilogin_id_db) ? $unilogin_id_db : '';
  
  $form['account']['unilogin_id'] = array (
    '#type' => 'textfield',
    '#title' => 'UNI Login id',
    '#default_value' => $unilogin_id,
    '#maxlength' => 60,
    '#description' => t('The user uni login id.'),
  );
  $form['#validate'][] = '_unilogin_form_user_edit_validate';
  $form['#submit'][] = '_unilogin_form_user_profile_submit';
}

function ntsnet_unilogin_form_alter(&$form, $form_state, $form_id) {
  if (!in_array($form_id, array('user_login', 'user_login_block'))) return;
  $form['#validate'][] = '_unilogin_user_login_validate';
}

/**
 * User edit form submit function.
 * 
 * @param array $form
 *   Drupal form array.
 * @param array $form_state
 *   Drupal form state array.
 */
function _unilogin_form_user_profile_submit($form, &$form_state){
  $values = $form_state['values'];
  $user = $form['_account']['#value'];
  // Save unilogin id.
  _unilogin_db_save_unilogin_id($user->uid, $values['unilogin_id']);
}

/**
 * User edit form validate function.
 * Validates unilogin related fields.
 * 
 * @param array $form
 *   Drupal form array.
 * @param array $form_state
 *   Drupal form state array.
 */
function _unilogin_form_user_edit_validate($form, &$form_state){
  $values = $form_state['values'];
  $user = $form['_account']['#value'];
  $uid_db = _unilogin_db_load_uid_by_unilogin_id($values['unilogin_id']);
  // If another user saved a record with the same unilogin_id set an error.
  if(!empty($uid_db) && $uid_db != $user->uid){
    form_set_error(
      'unilogin_id',
      t('Another user is already using the unilogin. Please pick another one.')
    );
  }
}

/**
 * Unilogin user validate function. Used for external authentication.
 * 
 * @param array $form
 *   Drupal form array.
 * @param array $form_state
 *   Drupal form state array.
 */
function _unilogin_user_login_validate($form, &$form_state){
  $values = $form_state['values'];
  _unilogin_authenticate($values['name']);
}

/**
 * Decide if we are in unilogin callback state.
 * @return type
 */
function _unilogin_is_in_unilogin_callback_state(){
  return !empty($_GET['user']) || !empty($_GET['auth']) || !empty($_GET['timestamp']);
}
